[package]
name = "devstack-app"
version.workspace = true
edition.workspace = true
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
devstack-core = { path = "../core" }
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true
