use std::path::PathBuf;

/// Generate a minimal httpd.conf that Includes our vhosts.d.
/// Locates Apache modules dynamically from brew prefix.
pub fn write_httpd_conf(paths: &crate::paths::Paths, http_port: u16) -> crate::Result<()> {
    let prefix = brew_prefix().unwrap_or_else(|| "/opt/homebrew".into());
    let server_root = format!("{prefix}/opt/httpd");
    let module_dir = format!("{server_root}/lib/httpd/modules");

    // modules we need — only include ones that exist
    let wanted = [
        "mod_mpm_event.so",
        "mod_dir.so",
        "mod_mime.so",
        "mod_log_config.so",
        "mod_authz_core.so",
        "mod_authz_host.so",
        "mod_unixd.so",
        "mod_alias.so",
        "mod_rewrite.so",
        "mod_proxy.so",
        "mod_proxy_fcgi.so",
        "mod_ssl.so",
        "mod_socache_shmcb.so",
        "mod_setenvif.so",
        "mod_headers.so",
        "mod_negotiation.so",
        "mod_autoindex.so",
        "mod_reqtimeout.so",
        "mod_env.so",
    ];

    let mut loads = String::new();
    for m in wanted {
        let p = PathBuf::from(format!("{module_dir}/{m}"));
        if p.exists() {
            let bare = m.strip_prefix("mod_").unwrap().strip_suffix(".so").unwrap();
            loads.push_str(&format!(
                "LoadModule {bare}_module {module_dir}/{m}\n"
            ));
        }
    }

    let conf = format!(
        r#"# Generated by devstack — do not edit
ServerRoot "{server_root}"

Listen {http_port}

{loads}
ServerName localhost

<Directory />
    AllowOverride none
    Require all denied
</Directory>

DocumentRoot "{docroot}"
<Directory "{docroot}">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

DirectoryIndex index.php index.html

<IfModule mime_module>
    TypesConfig {prefix}/opt/httpd/conf/mime.types
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
</IfModule>

ErrorLog "{logs}/httpd-error.log"
LogLevel warn
<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{{Referer}}i\" \"%{{User-Agent}}i\"" combined
</IfModule>

PidFile "{pid}"

<IfModule unixd_module>
    User {user}
    Group {group}
</IfModule>

# devstack vhosts
Include "{vhosts}/*.conf"
"#,
        server_root = server_root,
        http_port = http_port,
        loads = loads,
        docroot = paths.sites_root_default().display(),
        prefix = prefix,
        logs = paths.logs_dir().display(),
        pid = paths.pid_file("httpd").display(),
        user = std::env::var("USER").unwrap_or_else(|_| "_www".into()),
        group = if cfg!(target_os = "macos") { "staff" } else { "www-data" },
        vhosts = paths.vhosts_dir().display(),
    );

    std::fs::write(paths.httpd_conf(), conf)?;
    Ok(())
}

pub fn brew_prefix() -> Option<String> {
    if PathBuf::from("/opt/homebrew/bin/brew").exists() {
        Some("/opt/homebrew".into())
    } else if PathBuf::from("/usr/local/bin/brew").exists() {
        Some("/usr/local".into())
    } else {
        which::which("brew")
            .ok()
            .and_then(|p| p.parent().and_then(|p| p.parent()).map(|p| p.display().to_string()))
    }
}

pub fn httpd_bin() -> Option<PathBuf> {
    let prefix = brew_prefix()?;
    let p = PathBuf::from(format!("{prefix}/opt/httpd/bin/httpd"));
    p.exists().then_some(p)
}

pub fn start_httpd(paths: &crate::paths::Paths) -> crate::Result<()> {
    let httpd = httpd_bin()
        .ok_or_else(|| crate::Error::Config("httpd not found — brew install httpd".into()))?;
    crate::service::spawn_daemon(
        httpd.to_str().unwrap(),
        &["-f", paths.httpd_conf().to_str().unwrap(), "-k", "start"],
        &paths.pid_file("httpd"),
        &paths.log_file("httpd"),
    )?;
    Ok(())
}

pub fn stop_httpd(paths: &crate::paths::Paths) -> crate::Result<()> {
    crate::service::stop_daemon(&paths.pid_file("httpd"), 5)
}
