// Windows httpd — vendored Apache from ApacheLounge.
// Uses mod_proxy_fcgi (bundled) → php-cgi over TCP, same SetHandler as macOS.

use std::path::PathBuf;

/// Locate vendored httpd.exe
pub fn httpd_bin() -> Option<PathBuf> {
    crate::vendor::find_vendor_bin("httpd", "bin/httpd.exe")
}

/// Vendor Apache module dir: ~/.devstack/vendor/httpd/modules/
fn module_dir() -> Option<PathBuf> {
    let root = crate::paths::Paths::detect().ok()?.root.join("vendor/httpd/modules");
    root.exists().then_some(root)
}

/// Write httpd.conf for Windows — mod_proxy_fcgi → php-cgi TCP.
/// ApacheLounge zips include mod_proxy + mod_proxy_fcgi as standard modules,
/// so no third-party module download is needed. The vhost template uses
/// `SetHandler "proxy:fcgi://127.0.0.1:PORT"` which this config serves.
pub fn write_httpd_conf(paths: &crate::paths::Paths, http_port: u16) -> crate::Result<()> {
    let vendor_root = paths.root.join("vendor/httpd");
    let mod_dir = module_dir()
        .ok_or_else(|| crate::Error::Config("vendored httpd not found — run `devctl install httpd`".into()))?;

    // Windows uses winnt MPM — compiled into httpd.exe by ApacheLounge, so no
    // LoadModule line is needed. We drive php-cgi via Action/ScriptAlias
    // (mod_actions + mod_cgi): mod_proxy_fcgi hands php-cgi a proxy:-prefixed
    // SCRIPT_FILENAME it rejects, so the CGI route is the reliable Windows one.
    let wanted = [
        "mod_dir.so",
        "mod_mime.so",
        "mod_log_config.so",
        "mod_authz_core.so",
        "mod_authz_host.so",
        "mod_alias.so",
        "mod_rewrite.so",
        "mod_actions.so",         // ← Action directive for php-cgi
        "mod_cgi.so",             // ← executes php-cgi.exe per request
        "mod_ssl.so",
        "mod_socache_shmcb.so",
        "mod_setenvif.so",
        "mod_headers.so",
        "mod_negotiation.so",
        "mod_autoindex.so",
        "mod_reqtimeout.so",
        "mod_env.so",
    ];

    let mut loads = String::new();
    let mut missing = Vec::new();
    for m in wanted {
        let p = mod_dir.join(m);
        if p.exists() {
            let bare = m.strip_prefix("mod_").unwrap().strip_suffix(".so").unwrap();
            loads.push_str(&format!(
                "LoadModule {bare}_module \"{}\"\n",
                p.display().to_string().replace('\\', "/")
            ));
        } else {
            missing.push(m);
        }
    }
    if !missing.is_empty() {
        tracing::warn!("httpd modules not found, skipped: {}", missing.join(", "));
    }

    // one ScriptAlias per vendored PHP version → maps /devstack-php-{ver}/
    // to the php-cgi directory so Action can exec php-cgi.exe
    let mut aliases = String::new();
    for ver in crate::php::detect_vendored_phps(paths).unwrap_or_default() {
        let dir = crate::vendor::vendor_dir(paths)
            .join(format!("php-{ver}"))
            .display()
            .to_string()
            .replace('\\', "/");
        let mime = ver.replace('.', "-");
        aliases.push_str(&format!(
            "ScriptAlias /devstack-php-{mime}/ \"{dir}/\"\n\
             <Directory \"{dir}\">\n    \
             AllowOverride None\n    \
             Options None\n    \
             Require all granted\n\
             </Directory>\n"
        ));
    }

    let conf = format!(
        r#"# Generated by devstack — do not edit
ServerRoot "{vendor_root}"

Listen {http_port}

{loads}
ServerName localhost

<Directory />
    AllowOverride none
    Require all denied
</Directory>

DocumentRoot "{docroot}"
<Directory "{docroot}">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

DirectoryIndex index.php index.html

<IfModule mime_module>
    TypesConfig "{vendor_root}/conf/mime.types"
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
</IfModule>

ErrorLog "{logs}/httpd-error.log"
LogLevel warn
<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{{Referer}}i\" \"%{{User-Agent}}i\"" combined
</IfModule>

PidFile "{pid}"

# php-cgi ScriptAliases — one per vendored PHP version
{aliases}

# devstack vhosts
Include "{vhosts}/*.conf"
"#,
        vendor_root = vendor_root.display().to_string().replace('\\', "/"),
        http_port = http_port,
        loads = loads,
        docroot = paths.sites_root_default().display().to_string().replace('\\', "/"),
        logs = paths.logs_dir().display().to_string().replace('\\', "/"),
        pid = paths.pid_file("httpd").display().to_string().replace('\\', "/"),
        vhosts = paths.vhosts_dir().display().to_string().replace('\\', "/"),
        aliases = aliases,
    );

    std::fs::write(paths.httpd_conf(), conf)?;
    Ok(())
}

pub fn start_httpd(paths: &crate::paths::Paths) -> crate::Result<()> {
    let httpd = httpd_bin()
        .ok_or_else(|| crate::Error::Config("vendored httpd not found — `devctl install httpd`".into()))?;
    // Run httpd in the foreground (no -k start): -k installs/controls a Windows
    // service and returns immediately, which would store the wrong pid.
    crate::service::spawn_daemon(
        httpd.to_str().unwrap(),
        &["-f", paths.httpd_conf().to_str().unwrap()],
        &paths.pid_file("httpd"),
        &paths.log_file("httpd"),
    )?;
    Ok(())
}

pub fn stop_httpd(paths: &crate::paths::Paths) -> crate::Result<()> {
    crate::service::stop_daemon(&paths.pid_file("httpd"), 5)
}
