// Windows httpd — vendored Apache from ApacheLounge.

use std::path::PathBuf;

/// Locate vendored httpd.exe
pub fn httpd_bin() -> Option<PathBuf> {
    crate::vendor::find_vendor_bin("httpd", "bin/httpd.exe")
}

/// Vendor Apache module dir: ~/.devstack/vendor/httpd/modules/
fn module_dir() -> Option<PathBuf> {
    let root = crate::paths::Paths::detect().ok()?.root.join("vendor/httpd/modules");
    root.exists().then_some(root)
}

/// Write httpd.conf for Windows — mod_fcgid instead of proxy_fcgi for php-cgi.
pub fn write_httpd_conf(paths: &crate::paths::Paths, http_port: u16) -> crate::Result<()> {
    let vendor_root = paths.root.join("vendor/httpd");
    let mod_dir = module_dir()
        .ok_or_else(|| crate::Error::Config("vendored httpd not found — run `devctl install httpd`".into()))?;

    let wanted = [
        "mod_mpm_winnt.so",       // Windows uses winnt MPM, not event
        "mod_dir.so",
        "mod_mime.so",
        "mod_log_config.so",
        "mod_authz_core.so",
        "mod_authz_host.so",
        "mod_alias.so",
        "mod_rewrite.so",
        "mod_fcgid.so",           // ← for php-cgi
        "mod_ssl.so",
        "mod_socache_shmcb.so",
        "mod_setenvif.so",
        "mod_headers.so",
        "mod_negotiation.so",
        "mod_autoindex.so",
        "mod_reqtimeout.so",
        "mod_env.so",
    ];

    let mut loads = String::new();
    for m in wanted {
        let p = mod_dir.join(m);
        if p.exists() {
            let bare = m.strip_prefix("mod_").unwrap().strip_suffix(".so").unwrap();
            loads.push_str(&format!(
                "LoadModule {bare}_module \"{}\"\n",
                p.display().to_string().replace('\\', "/")
            ));
        }
    }

    let conf = format!(
        r#"# Generated by devstack — do not edit
ServerRoot "{}"

Listen {http_port}

{loads}
ServerName localhost

<Directory />
    AllowOverride none
    Require all denied
</Directory>

DocumentRoot "{docroot}"
<Directory "{docroot}">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

DirectoryIndex index.php index.html

<IfModule mime_module>
    TypesConfig "{vendor_root}/conf/mime.types"
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
</IfModule>

ErrorLog "{logs}/httpd-error.log"
LogLevel warn
<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{{Referer}}i\" \"%{{User-Agent}}i\"" combined
</IfModule>

PidFile "{pid}"

# fcgid settings — php-cgi pools
FcgidInitialEnv PHPRC "{etc}/php"
FcgidMaxProcesses 10
FcgidProcessLifeTime 300
FcgidIdleTimeout 60

# devstack vhosts
Include "{vhosts}/*.conf"
"#,
        vendor_root.display().to_string().replace('\\', "/"),
        http_port = http_port,
        loads = loads,
        docroot = paths.sites_root_default().display().to_string().replace('\\', "/"),
        vendor_root = vendor_root.display().to_string().replace('\\', "/"),
        logs = paths.logs_dir().display().to_string().replace('\\', "/"),
        pid = paths.pid_file("httpd").display().to_string().replace('\\', "/"),
        etc = paths.etc_dir().display().to_string().replace('\\', "/"),
        vhosts = paths.vhosts_dir().display().to_string().replace('\\', "/"),
    );

    std::fs::write(paths.httpd_conf(), conf)?;
    Ok(())
}

pub fn start_httpd(paths: &crate::paths::Paths) -> crate::Result<()> {
    let httpd = httpd_bin()
        .ok_or_else(|| crate::Error::Config("vendored httpd not found — `devctl install httpd`".into()))?;
    crate::service::spawn_daemon(
        httpd.to_str().unwrap(),
        &["-f", paths.httpd_conf().to_str().unwrap(), "-k", "start"],
        &paths.pid_file("httpd"),
        &paths.log_file("httpd"),
    )?;
    Ok(())
}

pub fn stop_httpd(paths: &crate::paths::Paths) -> crate::Result<()> {
    crate::service::stop_daemon(&paths.pid_file("httpd"), 5)
}
