[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/cli",
    "crates/app",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/you/devstack"

[workspace.dependencies]
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
dirs = "5"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
handlebars = "4"
which = "6"
nix = { version = "0.27", features = ["process", "signal", "fs"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
